#!/usr/bin/env ruby
# frozen_string_literal: true

test_dir = __dir__

$: << File.join(File.dirname(test_dir), "lib")
$: << test_dir

require_relative "./test_helper"

require "find"

if ARGV.empty? then
  Find.find(test_dir) do |path|
    next unless File.file?(path) && File.basename(path) =~ /\Atest_.*\.rb\Z/

    require path
  end
else
  ARGV.each do |f|
    require File.expand_path(f)
  end
end

