#!/usr/bin/env ruby


test_dir = __dir__

$: << File.join(File.dirname(test_dir), "lib")
$: << test_dir

require_relative './test_helper'

require 'find'
Find.find(test_dir) do |path|
  next unless File.file?(path) && File.basename(path) =~ /\Atest_.*\.rb\Z/
  require path
end

