# DO NOT EDIT - This file is automatically generated
# Make changes to Manifest.txt and/or Rakefile and regenerate
source "https://rubygems.org"
gemspec

group :development, :test do
  gem "debug"
  gem "heel"
  gem "progress_bar"
  gem "benchmark-ips"
end
