# frozen_string_literal: true

# DO NOT EDIT - This file is automatically generated
# Make changes to Manifest.txt and/or Rakefile and regenerate
source "https://rubygems.org"
gemspec

group :development, :test do
  gem "benchmark-ips"
  gem "debug"
  gem "faker"
  gem "heel", require: false
  gem "minitest", "~> 5.11"
  gem "minitest-focus", "~> 1.2"
  gem "minitest-junit", "~> 1.0"
  gem "progress_bar"
  gem "rake"
  gem "rdoc", "~> 6.3", require: false
  gem "rubocop", "~> 1.63", require: false
  gem "rubocop-faker", "~> 1.1", require: false
  gem "rubocop-github", "~> 0.20", require: false
  gem "rubocop-md", "~> 1.2", require: false
  gem "rubocop-minitest", "~> 0.35", require: false
  gem "rubocop-packaging", "~> 0.5", require: false
  gem "rubocop-performance", "~> 1.21", require: false
  gem "rubocop-rake", "~> 0.6", require: false
  gem "rubocop-thread_safety", "~> 0.5", require: false
  gem "simplecov", "~> 0.21", require: false
end
